version: '3'
services:
    jupyterlab:
        build: .
        image: python-container
        container_name: jupyter-test
        working_dir: /work
        volumes:
            - ./work:/work
        ports:
            - '8888:8888'
        command: jupyter-lab --ip 0.0.0.0 --allow-root --NotebookApp.token='' --NotebookApp.password=''
